---
- hosts: all
  become: yes
  tasks:
  - name: Update the apt package index
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: Install packages for apt add repository over HTTPS
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
      - python3-pip
  - name: Add Apt signing key from official docker repo
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  - name: add docker official repository for Debian Buster
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
      state: present
  - name: Install python-docker
    pip:
      name: "{{ deps }}"
    vars:
      deps:
      - docker
      - jsondiff
      - pyyaml
  - name: Index new repo into the cache
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: actually install docker
    apt:
      name: "docker-ce"
      state: latest
  - name: Add current user to docker group
    user:
      name: user
      groups: docker
      append: yes
  - name: Daemon.json with unsecure registry
    template:
      src: templates/daemon.json
      dest: /etc/docker/daemon.json
    register: daemonjson
  - name: restart docker if daemon.json changed
    service: 
      name: docker
      state: restarted
    when: daemonjson.changed    
  - name: Login to private registry
    become: yes
    docker_login:
      registry: 192.168.56.4:9999
      username: admin
      password: admin
    
